all: diophantine bee_count bee_removal word_count
diophantine: diophantine.c
	gcc diophantine.c -o ../outputs/diophantine
bee_count: bee_count.c 
	gcc bee_count.c -o ../outputs/bee_count
bee_removal: bee_removal.c 
	gcc bee_removal.c -o ../outputs/bee_removal
word_count: word_count.c 
	gcc word_count.c -o ../outputs/word_count
	