all: my_first_program calculator calculator_float dice
my_first_program: my_first_program.c
	gcc my_first_program.c -o ../outputs/my_first_program
calculator: calculator.c
	gcc calculator.c -o ../outputs/calculator
calculator_float: calculator_float.c
	gcc calculator_float.c -o ../outputs/calculator_float -lm
dice: dice.c
	gcc dice.c -o ../outputs/dice

