all: simple_bubble_sort complex_bubble_sort binary_search_database
simple_bubble_sort: simple_bubble_sort.c
	gcc simple_bubble_sort.c -o ../outputs/simple_bubble_sort
complex_bubble_sort: complex_bubble_sort.c
	gcc complex_bubble_sort.c -o ../outputs/complex_bubble_sort
binary_search_database: binary_search_database.c
	gcc binary_search_database.c -o ../outputs/binary_search_database
